name: Test build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Python ${{ matrix.python-version }}
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true

      - name: create environment
        run: |
          conda create -n testing python=${{ matrix.python-version }}
          conda init

      - name: install dependencies
        run: |
          conda activate testing
          conda env list
          conda install --file requirements.txt requirements-test.txt
          conda list

      - name: flake8
        run: |
          conda activate testing
          conda env list
          python -m flake8 uproot4 --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 uproot4 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: pytest
        run: |
          conda activate testing
          conda env list
          python -m pytest -vv tests
